-- AlterTable
ALTER TABLE "WfEvent" ADD COLUMN "isWorldFlight" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "WfEvent" ADD COLUMN "flightSuffix" TEXT NOT NULL DEFAULT '';
ALTER TABLE "WfEvent" ADD COLUMN "aircraftType" TEXT NOT NULL DEFAULT 'B738';
